### ISSUE TITLE
Install package on windows

### ISSUE THREAD

**Issue by dy** [ethereumjs/ethereumjs-lib#134]
Hi @ethereumjs team!
I am trying to install `npm install ethereumjs-lib` on windows machine and get the following:
```sh
c:\projects\hobber>npm install ethereumjs-lib

> secp256k1@2.0.10 install c:\projects\hobber\node_modules\devp2p-dpt\node_modul
es\secp256k1
> npm run rebuild


> secp256k1@2.0.10 rebuild c:\projects\hobber\node_modules\devp2p-dpt\node_modul
es\secp256k1
> node-gyp rebuild


c:\projects\hobber\node_modules\devp2p-dpt\node_modules\secp256k1>if not defined
 npm_config_node_gyp (node "C:\Users\dmitry\AppData\Roaming\npm\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
(node "" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit
status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\dmitry\AppData\Roaming\npm
\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs5\\node.exe" "C:\\Users\\dmitry\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd c:\projects\hobber\node_modules\devp2p-dpt\node_modules\secp256k1
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dmitry\AppData\Roaming\npm-cache\_logs\2017-10-09T16_35_30
_280Z-debug.log
hobber@1.0.0 c:\projects\hobber
`-- (empty)

npm WARN hobber@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.10 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dmitry\AppData\Roaming\npm-cache\_logs\2017-10-09T16_35_31
_232Z-debug.log
```

Is there some issue with paths?
BTW I had to run terminal as admin to install that.

**Comment by holgerd77** [comment]
Hi, this library is outdated (sorry for the confusion) and replaced by https://github.com/ethereumjs/ethereumjs-vm + various modular other libraries (see organization page). We will add an outdated message in the next couple of days cc @jwasinger .
